nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  shesha:
    npmAlwaysAuth: true
    npmAuthIdent: "MnRObjY2ZVE4R1U4Y1Bwb3dqSFN5Nnl6cUlmZmJ6elRnWjJ4Nk80VjZmRUNwc0ZzVUk5akpRUUo5OUNGQUNBQUFBQXI2QXhrQUFBU0FaRE8zeFRR"
    npmRegistryServer: "https://pkgs.dev.azure.com/boxfusion/_packaging/npm.boxfusion.co.za/npm/registry/"
