approvedGitRepositories:
  - "**"

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  shesha:
    npmAlwaysAuth: true
    npmAuthIdent: "Ym94ZnVzaW9uOkFyRzltbmFiSks3NURsejBLZUcyQ3A1OHYzMmlUZWZSRzRsbDBic2U4VUdTNnpuQkg3VHVKUVFKOTlDR0FDQUFBQUFyNkF4a0FBQVNBWkRPM2lvTg=="
    npmRegistryServer: "https://pkgs.dev.azure.com/boxfusion/_packaging/npm.boxfusion.co.za/npm/registry/"
