nmHoistingLimits: workspaces

nodeLinker: node-modules

npmScopes:
  shesha:
    npmAlwaysAuth: true
    npmAuthIdent: ""
    npmRegistryServer: "https://pkgs.dev.azure.com/boxfusion/_packaging/npm.boxfusion.co.za/npm/registry/"
